using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProductService.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class FixIdentitySequences : Migration
    {
        // The InitialCreate migration seeds Products/Categories/Departments with explicit
        // Ids. Postgres' `GENERATED BY DEFAULT AS IDENTITY` accepts the explicit values but
        // never advances the underlying sequence, so the next auto-Id insert collides with
        // a seeded row on PK_Products / PK_Categories / PK_Departments. Push each sequence
        // past the current MAX(Id) so future inserts don't clash.
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                SELECT setval(pg_get_serial_sequence('""Products""',    'Id'), COALESCE((SELECT MAX(""Id"") FROM ""Products""),    0) + 1, false);
                SELECT setval(pg_get_serial_sequence('""Categories""',  'Id'), COALESCE((SELECT MAX(""Id"") FROM ""Categories""),  0) + 1, false);
                SELECT setval(pg_get_serial_sequence('""Departments""', 'Id'), COALESCE((SELECT MAX(""Id"") FROM ""Departments""), 0) + 1, false);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Nothing to revert. Rolling sequences backwards would only reintroduce the
            // duplicate-key collision this migration is here to prevent.
        }
    }
}
